### ISSUE TITLE
Implement MINIO_BROWSER_REDIRECT_URL env var

### ISSUE THREAD

**Issue by TippyLion28** [ricsanfre/ansible-role-minio#13]
Hi,

For deployments behind a load balancer, it is important to be able to configure the MinIO environment variable “MINIO_BROWSER_REDIRECT_URL”

Currently, I don’t see a way of doing that using this role unless I’m missing something

**Comment by ricsanfre** [comment]
Hi @TippyLion28,

`minio_server_env_extra` can be used to provide any additional environment variable.

See

**Comment by TippyLion28** [comment]
Perfect, thank you :))
