### ISSUE TITLE
No support for cluster mode

### ISSUE THREAD

**Issue by S0obi** [ricsanfre/ansible-role-minio#2]
Hello there and thanks for this role,

From what I can see from README and role code, it seems not possible to provide a cluster mode configuration.
Other minio nodes need to be provided in `MINIO_VOLUMES` in config file.

An existing implementation with Ansible is actually present in [this other role](https://github.com/atosatto/ansible-minio).

I would love to see that coming here as this role is really complete in term of features.
Thanks in advance.

**Comment by ricsanfre** [comment]
Thanks @S0obi for your suggestion.
I have created a new PR #4 adding cluster deployment support.
