### ISSUE TITLE
Minio alias configuration for mc doesnt get updated

### ISSUE THREAD

**Issue by RubenMakandra** [ricsanfre/ansible-role-minio#9]
Hey,
Im not sure if it's a bug or intended behavior, but the role breaks after changing the minio root password of an already configured minio alias.   
The change gets applied to the minio server (via the minio env file), but not to the client, since the role only checks if an alias exists, but not if the parameter for the alias are still correct. This results in all of the following tasks that configure users etc. to fail and the role exiting with an error.  
A quick  solution would be always running  `mc alias set [...]` command (`Task Configure minio connection alias` in `configure_server.yml)` instead of only running it if the alias doesn't exist.  That would ensure that the alias always has the given configuration.  
Alternatively, as a prettier but more complicated solution  one could compare the alias configuration with values given as variable, and run the set alias commands only if there's a difference.

**Comment by RubenMakandra** [comment]
Created a pull request, with the changes I was able to change the `minio_root_password` for my existing alias without errors.

**Comment by ricsanfre** [comment]
Thanks @RubenMakandra. It is clearly a bug. Thanks for the PR
